services:
  App\Services\ExchangeRates\ExchangeRatesStrategyInterface:
    public: true

  App\Services\ExchangeRates\Strategies\NbpStrategy:
    public: true

parameters:
  available-codes:
    EUR:
      buy: -0.05
      sell: 0.07
    USD:
      buy: -0.05
      sell: 0.07
    BRL:
      buy: false
      sell: 0.15